version: "3.7"
services:
    app:
        build:
            args:
                user: lacc
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: gestao
        container_name: gestao-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - gestao
    nginx:
        image: nginx:alpine
        container_name: gestao-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - gestao
networks:
    gestao:
        driver: bridge
